// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iufldbwimhemxxyhelqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1ZmxkYndpbWhlbXh4eWhlbHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzcyNzAsImV4cCI6MjA2MTgxMzI3MH0._BlfgDii4jY2RXNNlxTER4l8ZBeY8PccXTXqZVyADZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);